Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2017
Var
// Seção de Declarações das variáveis 
Perimetro,Raio;Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Perimetro")
Leia(Raio)
Perimetro<-(2*3,14*Raio)
Escreva("Perimetro")

Fimalgoritmo